EMAIL = <ENTER YOUR EMAIL ID HERE>
EMAIL_PASSWORD = <ENTER YOUR EMAIL PASSWORD HERE>
HOST = 'localhost'
USER = 'root'
DB_PASSWORD = 'password123' #SQL DATABASE PASSWORD (edit if required)
MYSQL_DB = 'TVseries'